import type { AiLiteracyTopicSeed } from "./learning-preview-data";
import { FRIA_QMS_RUBRIC } from "./learning-governance-config";

export const aiMasteryCourseTopicSeeds: AiLiteracyTopicSeed[] = [
  {
    code: "aimas-portfolio-triage",
    title: "Portfolio en triage",
    summary: "Van losse AI-pilots naar een beheersbaar portfolio met waarde, risico en haalbaarheid.",
    pages: [
      {
        code: "van-losse-pilots-naar-ai-portfolio",
        title: "Van losse pilots naar AI-portfolio",
        summary: "Positioneer Mastery: van individueel gebruik naar proceseigenaarschap en governance.",
        type: "content",
        minutes: 20,
        blocks: [
          {
            id: "m01-hero",
            type: "hero",
            title: "Waarom AI Mastery?",
            subtitle: "AI Mastery gaat over borgen, beoordelen en opschalen: wie beslist, wie controleert en welk bewijs blijft achter?",
          },
          {
            id: "m01-paragraph",
            type: "paragraph",
            markdown:
              "Losse experimenten worden pas verantwoord als ze passen in een portfolio: met duidelijke doelen, eigenaarschap, risicotriage, controlepunten en een ritme voor review. Mastery is bedoeld voor rollen die AI-gebruik moeten inrichten of beoordelen, niet alleen gebruiken.",
          },
          {
            id: "m01-compliance-engineering",
            type: "callout",
            tone: "info",
            markdown:
              "AI Mastery is compliance engineering: technische keuzes worden gekoppeld aan beleid, risico, menselijke controle, logging, documentatie en bewijs. Het doel is niet meer complexiteit, maar aantoonbaar beheerste AI in echte processen.",
          },
          {
            id: "m01-ai-act-provisional-timeline",
            type: "callout",
            tone: "warning",
            source_ids: ["SRC-EP-OMNIBUS", "SRC-COUNCIL-OMNIBUS"],
            source_status: "provisional_agreement",
            last_verified_at: "2026-05-29",
            provisional: true,
            legal_review_required: true,
            markdown:
              "Status 29 mei 2026: Parlement en Raad melden een voorlopig akkoord met uitgestelde toepassing voor bepaalde high-risk verplichtingen. Gebruik dit als planningssignaal, niet als definitieve wettekst, totdat formele adoptie en publicatie rond zijn.",
          },
          {
            id: "m01-reflection",
            type: "reflection",
            prompt: "Welke AI-initiatieven, pilots of informele tools leven al in jouw team of organisatie?",
            placeholder: "In mijn team zie ik...",
            min_words: 35,
            save_personal: true,
          },
          {
            id: "m01-takeaways",
            type: "key_takeaways",
            title: "Mastery verschuift de vraag",
            items: [
              "Niet: kan de tool dit? Wel: is dit proces verantwoord ingericht?",
              "Niet: wie prompt? Wel: wie is eigenaar, reviewer en beslisser?",
              "Niet: eenmalig testen. Wel: blijven monitoren en verbeteren.",
            ],
          },
        ],
      },
      {
        code: "use-case-triage-op-waarde-risico-en-haalbaarheid",
        title: "Use-case triage op waarde, risico en haalbaarheid",
        summary: "Gebruik een praktisch triagekader om use cases te prioriteren of te stoppen.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m02-comparison",
            type: "comparison",
            title: "Waarde en risico in balans",
            left_label: "Laag risico / snel leren",
            right_label: "Hoog risico / eerst borgen",
            left_items: [
              "Interne samenvattingen",
              "Conceptteksten zonder persoonsgegevens",
              "Ideegeneratie of structurering",
              "Procesverbetering met anonieme data",
            ],
            right_items: [
              "HR-screening of beoordeling",
              "Klantbesluiten met financiele impact",
              "Persoonsgerichte scoring",
              "Gebruik van gevoelige of grootschalige data",
            ],
            left_color: "#e7f8f5",
            right_color: "#fff1f2",
          },
          {
            id: "m02-triage-matrix",
            type: "decision_matrix",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo"],
            target_cefr: "B2",
            title: "Use-case triage: waarde x risico",
            x_axis_label: "Businesswaarde",
            y_axis_label: "Risico en governance-last",
            quadrants: [
              {
                id: "start",
                title: "Start beheerst",
                subtitle: "Hoge waarde, laag risico",
                tone: "start",
                summary: "Goede kandidaten voor een eerste beheerst experiment.",
                actions: [
                  "Start met een beperkte scope en fictieve of geminimaliseerde data.",
                  "Leg owner, reviewstap en succescriteria vooraf vast.",
                  "Controleer output voordat die extern of operationeel gebruikt wordt.",
                ],
                checks: [
                  "Is de tool goedgekeurd voor de gebruikte data?",
                  "Kan een mens de output inhoudelijk beoordelen?",
                  "Is duidelijk wanneer je stopt of escaleert?",
                ],
                rule: "Snel leren mag, zolang datagrens, menselijke controle en logging zichtbaar zijn.",
                examples: [
                  {
                    id: "mail",
                    title: "Klantmail drafting",
                    description: "AI maakt een conceptantwoord dat een medewerker controleert.",
                    value: "Hoog",
                    risk: "Laag/middel bij geanonimiseerde context",
                  },
                  {
                    id: "faq",
                    title: "FAQ-generatie",
                    description: "AI maakt concept-FAQ's op basis van goedgekeurde productinformatie.",
                    value: "Middel",
                    risk: "Laag als claims worden gecontroleerd",
                  },
                ],
              },
              {
                id: "careful",
                title: "Eerst borgen",
                subtitle: "Hoge waarde, hoog risico",
                tone: "careful",
                summary: "Waardevol, maar alleen met governance-ontwerp en specialistische review.",
                actions: [
                  "Voer risicoanalyse en waar nodig DPIA/FRIA-input uit.",
                  "Ontwerp oversight, logging, bezwaar/herziening en incidentpad vooraf.",
                  "Laat HR, DPO, legal of compliance meebeslissen voordat je live gaat.",
                ],
                checks: [
                  "Raakt de output kansen, rechten, geld, werk of toegang tot diensten?",
                  "Is menselijke eindverantwoordelijkheid zichtbaar en bevoegd?",
                  "Zijn datakwaliteit, bias en transparantie aantoonbaar beheerst?",
                ],
                rule: "Niet versnellen voordat governance is ontworpen. Hoge waarde rechtvaardigt geen losse promptpilot.",
                examples: [
                  {
                    id: "cv",
                    title: "CV-screening",
                    description: "AI ondersteunt kandidaatordening. Behandel dit als hoog-impact en mogelijk hoog-risico.",
                    value: "Hoog",
                    risk: "Hoog door impact op kansen van mensen",
                  },
                  {
                    id: "credit",
                    title: "Krediet- of coulancebeoordeling",
                    description: "AI ondersteunt een financieel of klantimpactvol besluit.",
                    value: "Hoog",
                    risk: "Hoog door financiele en individuele impact",
                  },
                ],
              },
              {
                id: "later",
                title: "Later of eenvoudiger",
                subtitle: "Lage waarde, laag risico",
                tone: "later",
                summary: "Kan nuttig zijn, maar is vaak niet de beste eerste investering.",
                actions: [
                  "Gebruik standaardfuncties of bestaande automatisering als dat volstaat.",
                  "Houd governance licht, maar niet afwezig.",
                  "Prioriteer pas als er duidelijk volume of kwaliteitswinst is.",
                ],
                checks: [
                  "Lost AI echt een probleem op?",
                  "Is een regelgebaseerde oplossing eenvoudiger?",
                  "Is het beheer de opbrengst waard?",
                ],
                rule: "Laag risico is geen automatisch ja. Kies alleen AI als de waarde concreet is.",
                examples: [
                  {
                    id: "spelling",
                    title: "Spellingscorrectie",
                    description: "AI corrigeert interne tekst zonder gevoelige data.",
                    value: "Laag/middel",
                    risk: "Laag",
                  },
                  {
                    id: "translate",
                    title: "Interne vertaalhulp",
                    description: "AI vertaalt niet-vertrouwelijke interne tekst.",
                    value: "Middel",
                    risk: "Laag bij controle",
                  },
                ],
              },
              {
                id: "avoid",
                title: "Niet starten",
                subtitle: "Lage waarde, hoog risico",
                tone: "avoid",
                summary: "De governance-last en mogelijke schade wegen zwaarder dan de opbrengst.",
                actions: [
                  "Stop de use case of herformuleer hem naar een veiliger doel.",
                  "Vraag specialistische review voordat er data of tooling wordt getest.",
                  "Zoek een niet-AI alternatief of beperk de impact radicaal.",
                ],
                checks: [
                  "Is er sprake van monitoring van medewerkers, emoties of gedrag?",
                  "Kan het mensen sturen, uitsluiten of benadelen?",
                  "Is de zakelijke waarde onvoldoende om zware waarborgen te dragen?",
                ],
                rule: "Een hoog-risico use case met lage waarde hoort niet in de pilotportfolio.",
                examples: [
                  {
                    id: "emotion",
                    title: "Emotieherkenning medewerkers",
                    description: "AI probeert emoties uit camera, audio of communicatie af te leiden.",
                    value: "Laag",
                    risk: "Zeer hoog door grondrechten, privacy en werkcontext",
                  },
                  {
                    id: "behaviour",
                    title: "Gedragsscoring klanten",
                    description: "AI rangschikt klanten op gedragsdata zonder duidelijke proportionele noodzaak.",
                    value: "Laag/middel",
                    risk: "Hoog door privacy, uitlegbaarheid en reputatie",
                  },
                ],
              },
            ],
          },
          {
            id: "m02-hrais-building-blocks",
            type: "knowledge_cards",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EP-OMNIBUS", "SRC-COUNCIL-OMNIBUS"],
            source_status: "provisional_agreement",
            last_verified_at: "2026-05-29",
            provisional: true,
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "security"],
            target_cefr: "B2",
            cards: [
              {
                id: "risk-management",
                title: "Risicomanagement",
                text: "Leg doel, impact, risico's, mitigaties, eigenaar, reviewmomenten en stopcriteria vast voordat de use case live gaat.",
              },
              {
                id: "data-governance",
                title: "Datagovernance",
                text: "Beoordeel datakwaliteit, representativiteit, dataminimalisatie, biasrisico en toegestane inputcategorieen.",
              },
              {
                id: "technical-docs",
                title: "Technische documentatie",
                text: "Documenteer werking, beperkingen, configuratie, versie, evaluatie en wijzigingen zodat beheer en review mogelijk blijven.",
              },
              {
                id: "logging",
                title: "Logging en audit trail",
                text: "Bewaar relevante beslissingen, versies, uitzonderingen, incidenten en reviewuitkomsten fraudebestendig en proportioneel.",
              },
              {
                id: "oversight-ui",
                title: "Oversight UI",
                text: "Ontwerp schermen met waarschuwingen, onzekerheid, stopknop, override en duidelijke menselijke taakverdeling.",
              },
              {
                id: "robustness",
                title: "Accuracy, robustness en security",
                text: "Test prestaties, foutmodi, misbruik, promptinjectie, security en fallback voordat AI afhankelijk wordt in het proces.",
              },
            ],
          },
          {
            id: "m02-scenario",
            type: "scenario",
            situation:
              "Er liggen drie voorstellen: een notulen-samenvatter, AI-ranking van sollicitanten en AI-suggesties voor klantenservice-coulance.",
            question: "Wat is de beste governance-aanpak?",
            choices: [
              {
                id: "speed",
                label: "Alle drie tegelijk starten om innovatie te versnellen.",
                consequence: "Je mist impactverschillen en noodzakelijke controls.",
                is_recommended: false,
              },
              {
                id: "triage",
                label: "Per use case waarde, impact, data, toezicht en stopcriteria bepalen.",
                consequence: "Je prioriteert proportioneel en voorkomt dat hoge-impact cases onderbeheerst live gaan.",
                is_recommended: true,
              },
            ],
          },
          {
            id: "m02-download",
            type: "download",
            title: "Triagecanvas",
            description: "Leg waarde, risico, datagrens, betrokkenen, owner, oversight en bewijs vast.",
            file_url: "/downloads/learning/mastery-triagecanvas.csv",
            file_name: "mastery-triagecanvas.csv",
            mime_type: "text/csv",
            file_size_label: "CSV-template",
            label: "Template",
            button_label: "Open triagecanvas",
          },
        ],
      },
    ],
  },
  {
    code: "aimas-rollen-beleid-keten",
    title: "Rollen, beleid en keten",
    summary: "Maak provider, deployer, eigenaar, reviewer en escalatielijn expliciet.",
    pages: [
      {
        code: "rollen-gebruiker-deployer-provider-owner",
        title: "Rollen: gebruiker, deployer, provider, owner",
        summary: "Begrijp de ketenrollen en vertaal ze naar je eigen team.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m03-cards",
            type: "knowledge_cards",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "toolscope"],
            target_cefr: "B2",
            cards: [
              { id: "user", title: "Gebruiker", text: "De medewerker die AI in een concrete taak gebruikt." },
              { id: "deployer", title: "Deployer", text: "De organisatie of rol die AI inzet in een eigen procescontext." },
              { id: "provider", title: "Provider", text: "De partij die het AI-systeem ontwikkelt of aanbiedt." },
              { id: "owner", title: "Proceseigenaar", text: "De persoon die doel, grenzen, controles en evaluatie organiseert." },
              { id: "reviewer", title: "Reviewer", text: "De bevoegde persoon die output, uitzonderingen of incidenten beoordeelt." },
            ],
          },
          {
            id: "m03-chain-flow",
            type: "timeline",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "toolscope"],
            target_cefr: "B2",
            title: "Informatiestroom in de AI-keten",
            items: [
              {
                id: "provider",
                date: "1",
                title: "Provider levert systeeminformatie",
                description:
                  "Vraag documentatie, beperkingen, instructies, loggingmogelijkheden, dataverwerking en supportproces op.",
                highlight: true,
              },
              {
                id: "deployer",
                date: "2",
                title: "Deployer vertaalt naar organisatiebeleid",
                description:
                  "Bepaal toegestane use cases, dataklassen, training, toezicht, logging en escalatieroute.",
                highlight: true,
              },
              {
                id: "owner",
                date: "3",
                title: "Owner maakt procesafspraken",
                description:
                  "Leg vast wie mag gebruiken, wie reviewt, wanneer de stopknop geldt en welke evidence achterblijft.",
                highlight: false,
              },
              {
                id: "user",
                date: "4",
                title: "Gebruiker werkt binnen kaders",
                description:
                  "Gebruik alleen goedgekeurde tools, minimaliseer data, controleer output en meld twijfel of fouten.",
                highlight: false,
              },
            ],
          },
          {
            id: "m03-paragraph",
            type: "paragraph",
            markdown:
              "Een organisatie die een SaaS- of GenAI-tool inzet, kan in praktijk deployer-verantwoordelijkheden hebben. Daarom moet intern helder zijn wie eigenaar is van de use case, wie controleert en wie mag stoppen of overrulen.",
          },
          {
            id: "m03-gpai-supplier-due-diligence",
            type: "knowledge_cards",
            source_ids: ["SRC-EU-AIACT-NL"],
            source_status: "current_law",
            last_verified_at: "2026-05-29",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "toolscope", "security"],
            target_cefr: "B2",
            cards: [
              {
                id: "supplier",
                title: "Supplier due diligence",
                text: "Vraag naar modelinformatie, dataverwerking, beveiliging, subverwerkers, support, incidentproces en contractuele grenzen.",
              },
              {
                id: "gpai",
                title: "GPAI of externe modellen",
                text: "Controleer bij algemene AI-modellen welke beperkingen, gebruiksvoorwaarden, systeemkaarten en downstream-verplichtingen relevant zijn.",
              },
              {
                id: "chain",
                title: "Keteninformatie",
                text: "Zorg dat providerinformatie doorvertaald wordt naar deployer-instructies, gebruikersrichtlijnen en lokale controls.",
              },
            ],
          },
          {
            id: "m03-short",
            type: "short_answer",
            question: "Welke rol heeft jouw team waarschijnlijk bij de belangrijkste AI-use case: gebruiker, deployer, owner of reviewer? Motiveer kort.",
            placeholder: "Mijn team is vooral...",
            min_words: 35,
          },
        ],
      },
      {
        code: "beleid-naar-proces-en-rolafspraken",
        title: "Beleid naar proces- en rolafspraken",
        summary: "Zet centraal beleid om in lokale afspraken, exceptions, RACI en audit trail.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m04-accordion",
            type: "accordion",
            title: "Minimale governance-elementen",
            allow_multiple_open: true,
            items: [
              { id: "policy", question: "Policy", answer: "Welke regels gelden voor tools, data en gebruikssituaties?" },
              { id: "exception", question: "Exception flow", answer: "Hoe vraag je goedkeuring voor afwijkingen of nieuwe use cases?" },
              { id: "owner", question: "Owner", answer: "Wie is verantwoordelijk voor doel, werking, review en wijzigingen?" },
              { id: "reviewer", question: "Reviewer", answer: "Wie controleert output, incidenten en uitzonderingen?" },
              { id: "audit", question: "Audit trail", answer: "Welke besluiten, scores, logs en versies worden bewaard?" },
            ],
          },
          {
            id: "m04-checklist",
            type: "checklist",
            title: "Governance-minimumset",
            items: [
              "Goedgekeurde use case en doel",
              "Proceseigenaar en reviewer",
              "Dataregels en verboden invoer",
              "Oversightmodel en stopcriteria",
              "Logging, escalatiepad en reviewmoment",
            ],
            require_all: true,
          },
          {
            id: "m04-download",
            type: "download",
            title: "RACI-template",
            description: "Leg Responsible, Accountable, Consulted en Informed per AI-processtap vast.",
            file_url: "/downloads/learning/mastery-raci-template.csv",
            file_name: "mastery-raci-template.csv",
            mime_type: "text/csv",
            file_size_label: "CSV-template",
            label: "Template",
            button_label: "Open RACI-template",
          },
        ],
      },
    ],
  },
  {
    code: "aimas-oversight-controles",
    title: "Oversight en controles",
    summary: "Ontwerp human oversight, approval gates, override, sampling en stopcriteria.",
    pages: [
      {
        code: "human-oversight-by-design",
        title: "Human oversight by design",
        summary: "Bouw menselijk toezicht in het proces, niet als losse nagedachte.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m05-hero",
            type: "hero",
            title: "HITL, HOTL en HIC ontwerpen",
            subtitle: "Oversight werkt pas als iemand bevoegd, getraind en ondersteund is om output te negeren, overrulen of stoppen.",
          },
          {
            id: "m05-timeline",
            type: "timeline",
            title: "Decision gate flow",
            items: [
              { id: "intake", date: "1", title: "Intake", description: "Use case, data en impact worden geregistreerd.", highlight: false },
              { id: "risk", date: "2", title: "Triage", description: "Waarde, risico en betrokkenen worden beoordeeld.", highlight: true },
              { id: "gate", date: "3", title: "Approval gate", description: "Bevoegde reviewer keurt start of wijziging goed.", highlight: false },
              { id: "monitor", date: "4", title: "Monitoring", description: "Steekproeven, signalen en klachten worden gevolgd.", highlight: false },
              { id: "stop", date: "5", title: "Stopcriteria", description: "Bij afwijking kan het proces worden gepauzeerd of gestopt.", highlight: false },
            ],
          },
          {
            id: "m05-scenario",
            type: "scenario",
            situation:
              "Een AI-assistent adviseert automatisch of een klant coulance krijgt. Het bedrag kan oplopen tot 500 euro.",
            question: "Waar hoort de approval gate?",
            choices: [
              {
                id: "none",
                label: "Geen gate; AI geeft alleen advies.",
                consequence: "Ook advies kan gedrag sturen en financieel effect hebben.",
                is_recommended: false,
              },
              {
                id: "threshold",
                label: "Menselijke goedkeuring boven drempelbedrag of bij afwijkende gevallen.",
                consequence: "Je koppelt oversight aan impact en uitzonderingen.",
                is_recommended: true,
              },
            ],
          },
        ],
      },
      {
        code: "override-sampling-vier-ogen-en-stopcriteria",
        title: "Override, sampling, vier-ogen en stopcriteria",
        summary: "Maak controle ingrijpbaar: vooraf, achteraf, steekproefsgewijs of via stopknop.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m06-comparison",
            type: "comparison",
            title: "Controlemechanismen",
            left_label: "Vooraf of realtime",
            right_label: "Achteraf of periodiek",
            left_items: ["Pre-approval", "Vier-ogencontrole", "Realtime override", "Stopknop bij signalen"],
            right_items: ["Sampling", "Kwaliteitsreview", "Incidentanalyse", "Periodieke herbeoordeling"],
            left_color: "#e7f8f5",
            right_color: "#e7f5ff",
          },
          {
            id: "m06-control-interventions-timeline",
            type: "timeline",
            title: "Vier controle-interventies",
            items: [
              {
                id: "pre-approval",
                date: "1",
                title: "Pre-approval",
                description:
                  "Een bevoegde owner of reviewer keurt de use case, datagrens en controls goed voordat AI in het proces wordt gebruikt.",
                highlight: true,
              },
              {
                id: "four-eyes",
                date: "2",
                title: "Vier-ogencontrole",
                description:
                  "Een tweede mens controleert AI-output bij hogere impact, twijfel, uitzonderingen of externe communicatie.",
                highlight: true,
              },
              {
                id: "sampling",
                date: "3",
                title: "Steekproef",
                description:
                  "Bij hoog volume review je periodiek een representatieve set output om fouten, bias en drift zichtbaar te maken.",
                highlight: false,
              },
              {
                id: "stop-override",
                date: "4",
                title: "Stopknop en override",
                description:
                  "Mensen hebben expliciete bevoegdheid om output te negeren, het proces te pauzeren en escalatie te starten.",
                highlight: false,
              },
            ],
          },
          {
            id: "m06-callout",
            type: "callout",
            tone: "warning",
            markdown:
              "Automation bias ontstaat wanneer mensen AI-advies sneller volgen omdat het systeem betrouwbaar lijkt. Ontwerp daarom actieve tegenspraak en duidelijke override-macht.",
          },
          {
            id: "m06-reflection",
            type: "reflection",
            prompt: "Welke stopknop of override heeft jouw belangrijkste AI-proces nodig?",
            placeholder: "Het proces moet stoppen of escaleren wanneer...",
            min_words: 35,
            save_personal: true,
          },
        ],
      },
    ],
  },
  {
    code: "aimas-data-bias-monitoring",
    title: "Data, bias en monitoring",
    summary: "Organiseer datakwaliteit, representativiteit, logging, review en incidentmanagement.",
    pages: [
      {
        code: "datakwaliteit-representativiteit-en-bias",
        title: "Datakwaliteit, representativiteit en bias",
        summary: "Herken fairness- en kwaliteitsrisico's in datasets, processen en output.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m07-cards",
            type: "knowledge_cards",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo"],
            target_cefr: "B2",
            cards: [
              {
                id: "quality",
                title: "Datakwaliteit",
                text: "Controleer of data juist, actueel, relevant, compleet genoeg en passend voor het doel is. Slechte input maakt goede governance onmogelijk.",
              },
              {
                id: "represent",
                title: "Representativiteit",
                text: "Controleer of relevante groepen, situaties en uitzonderingen niet structureel ontbreken. Ontbrekende perspectieven worden vaak onzichtbare foutbronnen.",
              },
              {
                id: "fairness",
                title: "Bias en fairness",
                text: "Beheers non-discriminatierisico door foutpercentages, proxies en impact per groep te monitoren. Formuleer dit als aantoonbare risicobeheersing, niet als garantie.",
              },
              {
                id: "drift",
                title: "Model drift",
                text: "Prestaties kunnen dalen wanneer data, gedrag, markt of proces verandert. Leg drempelwaarden, reviewritme en retraining- of stopcriteria vast.",
              },
            ],
          },
          {
            id: "m07-bias-checklist",
            type: "checklist",
            title: "Bias- en datakwaliteitscheck",
            items: [
              "Datadoel en dataminimalisatie zijn beschreven",
              "Representativiteit en ontbrekende groepen zijn beoordeeld",
              "Proxyvariabelen zoals postcode, taalniveau of kanaal zijn besproken",
              "Foutpercentages worden niet alleen gemiddeld, maar ook per relevante groep bekeken",
              "Drift-signalen, reviewritme en stopcriteria zijn vastgelegd",
            ],
            require_all: true,
          },
          {
            id: "m07-case",
            type: "case_lab",
            title: "Bias-risico in HR of operations",
            markdown:
              "Beoordeel een use case waarin AI kandidaten rangschikt of operationele prioriteiten voorspelt. Benoem welke data kan ontbreken, wie geraakt wordt en welke menselijke controle nodig is.",
            reflection_prompt: "Welke check zou je periodiek uitvoeren om bias of drift te signaleren?",
          },
          {
            id: "m07-takeaways",
            type: "key_takeaways",
            title: "Monitoring begint voor livegang",
            items: [
              "Definieer wat goede output betekent.",
              "Leg foutsignalen en grenswaarden vooraf vast.",
              "Controleer niet alleen gemiddelden maar ook impact op groepen.",
            ],
          },
        ],
      },
      {
        code: "monitoring-logs-en-incidenten",
        title: "Monitoring, logs en incidenten",
        summary: "Richt audit trail, reviewcyclus en incidentpad in.",
        type: "content",
        minutes: 30,
        blocks: [
          {
            id: "m08-heading",
            type: "heading",
            text: "Bewijsbare beheersing",
            level: 2,
          },
          {
            id: "m08-timeline",
            type: "timeline",
            title: "Monitoringcyclus: van log naar verbetering",
            items: [
              { id: "log", date: "1", title: "Loggen", description: "Leg use case, versie, inputcategorie, outputstatus, reviewer en besluit vast. Maak bewaartermijn en toegang doelgebonden.", highlight: false },
              { id: "signal", date: "2", title: "Signaleren", description: "Monitor fouten, klachten, afwijkingen, bias, drift en uitzonderingen. Leg drempelwaarden vooraf vast.", highlight: true },
              { id: "incident", date: "3", title: "Incident beoordelen", description: "Classificeer ernst, eigenaar en noodzakelijke actie. Bij datalekken loopt de AVG-meldroute via privacy officer/DPO.", highlight: false },
              { id: "review", date: "4", title: "Review en bijstellen", description: "Evalueer controls, training, datakwaliteit, leverancier en proceswijzigingen. Documenteer het besluit.", highlight: false },
            ],
          },
          {
            id: "m08-fria-qms-sandbox",
            type: "accordion",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-RIJK-TOEZICHT", "SRC-UAIV"],
            source_status: "draft_national_law",
            last_verified_at: "2026-05-29",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo"],
            target_cefr: "B2",
            review_rubric: FRIA_QMS_RUBRIC,
            title: "Advanced governance-artefacten",
            allow_multiple_open: true,
            items: [
              {
                id: "fria",
                question: "FRIA-input pack",
                answer:
                  "Voor impactvolle of mogelijk hoog-risico use cases verzamel je doel, doelgroep, betrokkenenimpact, datacategorieen, rechten, oversight, risico's en mitigaties als input voor juridische of compliance-review.",
              },
              {
                id: "qms",
                question: "QMS / ISO 42001-control map",
                answer:
                  "Vertaal beleid naar terugkerende controls: eigenaar, change management, testcriteria, incidentproces, training, leveranciersbeheer en managementreview.",
              },
              {
                id: "sandbox",
                question: "Sandbox-intake",
                answer:
                  "Bij innovatieve of onzekere toepassingen kan een intake-memo helpen: beoogd gebruik, risico's, vragen aan toezichthouder of expert, testopzet en bewijs dat je vroegtijdig hebt getoetst.",
              },
            ],
          },
          {
            id: "m08-download",
            type: "download",
            title: "Incident- en reviewregister",
            description: "Template voor logging, incidentclassificatie, reviewbesluit en opvolgactie.",
            file_url: "/downloads/learning/mastery-incident-reviewregister.csv",
            file_name: "mastery-incident-reviewregister.csv",
            mime_type: "text/csv",
            file_size_label: "CSV-template",
            label: "Register",
            button_label: "Open register",
          },
        ],
      },
    ],
  },
  {
    code: "aimas-adoptie-implementatie",
    title: "Adoptie en implementatie",
    summary: "Maak transparantie, betrokkenencommunicatie en teamadoptie praktisch uitvoerbaar.",
    pages: [
      {
        code: "transparantie-en-betrokkenencommunicatie",
        title: "Transparantie en betrokkenencommunicatie",
        summary: "Weet wanneer disclosure, uitleg of informatie richting klant of medewerker nodig is.",
        type: "content",
        minutes: 25,
        blocks: [
          {
            id: "m09-paragraph",
            type: "paragraph",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo", "hr"],
            target_cefr: "B2",
            markdown:
              "Transparantie betekent dat betrokkenen niet onnodig in het duister blijven over AI-gebruik dat hen raakt. Bij synthetische content, HR-contexten of besluitondersteuning kan extra uitleg, disclosure of procedurele bescherming nodig zijn.",
          },
          {
            id: "m09-disclosure-slides",
            type: "slide_deck",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo", "hr"],
            target_cefr: "B2",
            title: "Transparantie en disclosure",
            show_thumbnails: true,
            slides: [
              {
                id: "s1",
                title: "Wanneer moet je AI-gebruik uitleggen?",
                url: "/learning/slide-placeholder.svg",
                alt: "Slide over transparantiemomenten",
                notes:
                  "Analyseer disclosure vooral bij AI-contact met mensen, synthetische media, emotie- of categorisatiecontexten en besluitondersteuning met impact. Formuleer dit per use case en laat juridische randgevallen reviewen.",
                interaction: { type: "none" },
              },
              {
                id: "s2",
                title: "Gate scenario: synthetische marketingvideo",
                url: "/learning/slide-placeholder.svg",
                alt: "Slide met disclosure-scenario over synthetische media",
                notes:
                  "Een synthetische testimonial of deepfake-achtige video moet niet misleiden. In veel situaties is duidelijke labeling nodig; laat publieke campagnecopy vooraf reviewen.",
                interaction: {
                  type: "multiple_choice",
                  question: "Wat is de veiligste eerste aanpak voor een synthetische testimonialvideo?",
                  options: [
                    { id: "hide", label: "Niet vermelden als het overtuigend lijkt.", is_correct: false },
                    { id: "small", label: "Alleen in kleine lettertjes achteraf noemen.", is_correct: false },
                    { id: "label", label: "Duidelijk labelen als AI-gegenereerd en campagne vooraf laten reviewen.", is_correct: true },
                  ],
                  feedback_correct: "Goed: transparantie, niet-misleiding en review horen bij elkaar.",
                  feedback_incorrect: "Kies een aanpak die zichtbaar, controleerbaar en niet-misleidend is.",
                },
              },
              {
                id: "s3",
                title: "Gate scenario: HR-besluitondersteuning",
                url: "/learning/slide-placeholder.svg",
                alt: "Slide met disclosure-scenario over HR",
                notes:
                  "Bij HR-contexten is alleen melden meestal niet genoeg. Beoordeel doel, grondslag, rechten, menselijke herziening, biasrisico en DPO/HR-review voordat het proces live gaat.",
                interaction: {
                  type: "multiple_choice",
                  question: "Een sollicitant vraagt of AI is gebruikt bij de selectie. Wat is de veiligste route?",
                  options: [
                    { id: "none", label: "Niets zeggen omdat de recruiter uiteindelijk beslist.", is_correct: false },
                    { id: "basic", label: "Alleen zeggen dat AI is gebruikt, zonder verdere uitleg.", is_correct: false },
                    { id: "explain", label: "Uitleg geven over de rol van AI en een menselijke herzieningsroute bieden volgens beleid.", is_correct: true },
                  ],
                  feedback_correct: "Goed: uitleg, menselijke herziening en beleid/DPO-review horen bij HR-impact.",
                  feedback_incorrect: "Bij HR-impact is transparantie gekoppeld aan rechten, menselijke controle en uitlegbaarheid.",
                },
              },
            ],
          },
          {
            id: "m09-scenario",
            type: "scenario",
            source_ids: ["SRC-EU-AIACT-NL", "SRC-EC-QA"],
            source_status: "current_law",
            last_verified_at: "2026-05-31",
            legal_review_required: true,
            review_required: true,
            review_tags: ["legal", "ai_act", "privacy", "dpo", "hr"],
            situation:
              "Marketing wil een synthetische testimonialvideo publiceren en HR wil AI gebruiken om sollicitatiebrieven te rangschikken.",
            question: "Wat is de juiste Mastery-reactie?",
            choices: [
              {
                id: "campaign",
                label: "Marketing mag live; HR mag starten zolang het snel resultaat geeft.",
                consequence: "Je negeert disclosure, arbeidsimpact en governance.",
                is_recommended: false,
              },
              {
                id: "govern",
                label: "Per use case disclosure, rechten, reviewflow, logging en toestemming/beleid beoordelen.",
                consequence: "Je koppelt transparantie en rechten aan de concrete impact.",
                is_recommended: true,
              },
            ],
          },
          {
            id: "m09-short",
            type: "short_answer",
            question: "Hoe zou je in begrijpelijke taal uitleggen dat AI een proces ondersteunt, maar niet zelfstandig beslist?",
            placeholder: "In dit proces gebruiken we AI om...",
            min_words: 40,
          },
        ],
      },
      {
        code: "adoptieplan-voor-een-mkb-team",
        title: "Adoptieplan voor een MKB-team",
        summary: "Ontwerp een realistische invoering met training, uitzonderingen, eigenaarschap en refresh.",
        type: "case",
        minutes: 25,
        blocks: [
          {
            id: "m10-case",
            type: "case_lab",
            title: "Klein beginnen, strak borgen",
            markdown:
              "Maak een invoeringsplan voor een MKB-team dat AI wil gebruiken in klantenservice. Beschrijf startscope, training, approved tools, uitzonderingen, owner, reviewer, escalatie en eerste reviewmoment.",
            reflection_prompt:
              "Welke afspraak maakt het verschil tussen vrijblijvend experimenteren en beheerst invoeren?",
          },
          {
            id: "m10-checklist",
            type: "checklist",
            title: "Adoptieplan compleet",
            items: [
              "Scope en niet-scope",
              "Gebruikersgroep en training",
              "Goedgekeurde tools en dataregels",
              "Owner, reviewer en escalatiepad",
              "Reviewmoment en refresh-trigger",
            ],
            require_all: true,
          },
        ],
      },
    ],
  },
  {
    code: "aimas-praktijkcase-certificering",
    title: "Praktijkcase en certificering",
    summary: "Toon governance-bekwaamheid met een integrale case, essay, scenario's en intern bewijs.",
    pages: [
      {
        code: "governance-praktijkcase",
        title: "Governance-praktijkcase",
        summary: "Ontwerp governance voor klantenservice-samenvattingen en HR-screening.",
        type: "case",
        minutes: 50,
        blocks: [
          {
            id: "m11-case",
            type: "case_lab",
            title: "AI in klantenservice en HR",
            markdown:
              "Een MKB-bedrijf wil AI inzetten voor klantenservice-samenvattingen en eerste HR-screening. Lever een governance-ontwerp op met triage, rollen, dataregels, oversight, logging, disclosure, escalatie en implementatiestappen.",
            reflection_prompt:
              "Motiveer waarom de klantenservice-use case anders geborgd wordt dan de HR-use case.",
            reviewer_guidance:
              "Beoordeel of de learner governance op procesniveau kan ontwerpen. De HR-use case vraagt zwaardere borging dan klantenservice-samenvattingen. Keur af als oversight, logging of betrokkenenimpact ontbreekt.",
            evidence_items: [
              "Waarde/risico/haalbaarheid per use case is afgewogen.",
              "Owner, reviewer en bevoegdheden zijn toegewezen.",
              "Dataregels en verboden invoer zijn concreet.",
              "Human oversight, override en stopcriteria zijn ontworpen.",
              "Logging, disclosure, escalatie en reviewritme zijn opgenomen.",
            ],
            review_rubric: [
              {
                id: "risk-triage",
                title: "Risicotriage",
                sufficient: "Waarde, risico en haalbaarheid zijn logisch afgewogen per use case.",
                strong: "De learner past proportionaliteit toe en onderscheidt HR scherp van klantenservice.",
                hard_fail: "HR-screening wordt als lage-impact of puur technisch vraagstuk behandeld.",
              },
              {
                id: "governance-design",
                title: "Governance-ontwerp",
                sufficient: "Rollen, processtappen, checks en uitzonderingen zijn aanwezig.",
                strong: "Het ontwerp is realistisch voor een MKB-team met beperkte capaciteit.",
                hard_fail: "Er is geen eigenaar, reviewer of escalatiepad.",
              },
              {
                id: "human-oversight",
                title: "Human oversight",
                sufficient: "Oversightmodel, bevoegdheid en stopcriteria zijn passend gekozen.",
                strong: "Override, vier-ogencontrole of sampling is gekoppeld aan impactdrempels.",
                hard_fail: "AI kan personele of klantimpact sturen zonder menselijke controle.",
              },
              {
                id: "evidence-transparency",
                title: "Evidence en transparantie",
                sufficient: "Logging, disclosure en reviewmomenten zijn benoemd.",
                strong: "Evidence is versioneerbaar en geschikt voor interne assurance.",
                hard_fail: "Geen audit trail of geen aandacht voor betrokkenencommunicatie.",
              },
            ],
          },
          {
            id: "m11-checklist",
            type: "checklist",
            title: "Minimale controls",
            items: [
              "Waarde/risico/haalbaarheid per use case",
              "Owner, reviewer en bevoegdheden",
              "Dataregels en verboden invoer",
              "Human oversight, override en stopcriteria",
              "Logging, disclosure en reviewritme",
              "Supplier/GPAI-informatie en relevante beperkingen",
              "FRIA-, QMS- of sandbox-artefacten waar de impact daarom vraagt",
            ],
            require_all: true,
          },
          {
            id: "m11-essay",
            type: "quiz_essay",
            question:
              "Motiveer in 150-250 woorden je governance-aanpak. Besteed aandacht aan human oversight, transparantie, evidence en MKB-uitvoerbaarheid.",
            min_words: 150,
            max_words: 250,
            manual_review_required: true,
            reviewer_guidance:
              "Gebruik het essay om te toetsen of de governance-keuzes bewust en verdedigbaar zijn. Een goed antwoord benoemt trade-offs, niet alleen losse controls.",
            evidence_items: [
              "Motivatie voor gekozen oversightmodel.",
              "Uitleg van transparantie richting klant of medewerker.",
              "Evidence/logging die achteraf toetsbaar is.",
              "Praktische uitvoerbaarheid voor MKB-context.",
            ],
            review_rubric: [
              {
                id: "motivation",
                title: "Motivering",
                sufficient: "Keuzes worden inhoudelijk gemotiveerd.",
                strong: "De learner benoemt expliciet waarom alternatieven minder passend zijn.",
                hard_fail: "Alleen generieke beleidswoorden zonder concrete toepassing.",
              },
              {
                id: "oversight",
                title: "Oversight",
                sufficient: "Menselijke controle, bevoegdheid en stopcriteria zijn genoemd.",
                strong: "Oversight is gekoppeld aan risico, impact en procesmoment.",
                hard_fail: "Geen menselijke controle bij impactvolle AI-inzet.",
              },
              {
                id: "evidence",
                title: "Evidence",
                sufficient: "Er is duidelijk wat wordt vastgelegd en waarom.",
                strong: "Evidence bevat versie, owner, reviewmoment en besluitlog.",
                hard_fail: "Geen logging of reviewbasis.",
              },
            ],
          },
        ],
      },
      {
        code: "mastery-assessment",
        title: "Mastery assessment",
        summary: "Toets gevorderde governancekennis, scenario-oordeel en betekenis van certificering.",
        type: "assessment",
        minutes: 50,
        blocks: [
          {
            id: "m12-mcq",
            type: "quiz_multiple_choice",
            question: "Wat is de beste eerste governancevraag bij een nieuwe AI-use case?",
            options: [
              { id: "popular", label: "Welke tool is populair?" },
              { id: "prompt", label: "Welke prompt werkt het snelst?" },
              { id: "impact", label: "Welk besluit ondersteunt AI, wie beslist en wat is de impact?" },
              { id: "speed", label: "Hoe snel kunnen we live?" },
            ],
            correct_option_id: "impact",
            explanation: "Governance start bij besluit, impact en verantwoordelijkheid.",
          },
          {
            id: "m12-ms",
            type: "quiz_multiple_select",
            question: "Welke elementen horen in een governance-minimumset?",
            options: [
              { id: "owner", label: "Owner" },
              { id: "data", label: "Dataregels" },
              { id: "oversight", label: "Oversight en escalatiepad" },
              { id: "hype", label: "Een populaire toolnaam als enige documentatie" },
            ],
            correct_option_ids: ["owner", "data", "oversight"],
            explanation: "Een toolkeuze is geen governance-ontwerp.",
          },
          {
            id: "m12-tf",
            type: "quiz_true_false",
            question:
              "Een intern RouteAI-certificaat betekent automatisch dat de organisatie juridisch volledig compliant is met Article 4.",
            correct_answer: false,
            explanation:
              "Het certificaat is interne evidence van bekwaamheid, geen wettelijke vrijwaring of externe audit.",
          },
          {
            id: "m12-short",
            type: "short_answer",
            question: "Noem drie onderdelen van een praktisch stop- of override-mechanisme.",
            placeholder: "Een stopmechanisme bevat...",
            min_words: 35,
          },
          {
            id: "m12-hero",
            type: "hero",
            title: "AI Mastery behaald",
            subtitle: "Je toont aan dat je AI-use cases op team- en procesniveau kunt wegen, inrichten en borgen.",
          },
          {
            id: "m12-disclaimer",
            type: "callout",
            tone: "info",
            markdown:
              "AI Mastery is een interne competentiebeoordeling. Het is geen juridisch oordeel, geen externe audit en geen formele AI Act-certificering.",
          },
        ],
      },
    ],
  },
];
