// Scenario definitions for the SAI Synthetic Pilot Organisatie.
//
// Every field here must match docs/sai-synthetic-flow-testplan.md exactly —
// that document hand-computes the expected calculate_v8_score(...) output
// for each scenario. If you change an answer code here, update the matching
// calculation in the testplan too.

import type { ScenarioDefinition } from "./types";

export const SCENARIOS: ScenarioDefinition[] = [
  {
    id: "no-ai-use",
    label: "Scenario 1 — Geen AI-gebruik",
    departments: ["marketing_communicatie", "sales_account", "operations"],
    defaultRepeat: 6,
    profile: {
      ai_frequency_code: "never",
      no_ai_reason_code: "geen_waarde",
    },
    dataTypeCodes: [],
  },
  {
    id: "approved-low-risk",
    label: "Scenario 2 — Goedgekeurde tool, laag risico",
    departments: ["marketing_communicatie"],
    defaultRepeat: 7,
    profile: {
      department_code: "marketing_communicatie",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "approved-sensitive-data",
    label: "Scenario 3 — Goedgekeurde tool met gevoelige/special-category data",
    departments: ["hr_recruitment"],
    defaultRepeat: 4,
    profile: {
      department_code: "hr_recruitment",
      ai_frequency_code: "daily",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["special_personal_data"],
    tool: {
      tool_code: "chatgpt_enterprise",
      tool_name: "ChatGPT Enterprise",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "klantenservice",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "unknown-tool-private-account",
    label: "Scenario 4 — Onbekende tool met privé-account",
    departments: ["it_data_development"],
    defaultRepeat: 4,
    profile: {
      department_code: "it_data_development",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["customer_data"],
    tool: {
      tool_name: "Onbekende schrijfassistent",
      is_custom: true,
      catalog_beheerstatus_code: "unknown",
      use_case_code: "klantenservice",
      context_codes: ["klantgerichte_toepassing"],
      account_type_code: "personal_free",
      registerDiscovery: true,
    },
  },
  {
    id: "prohibited-high-exposure",
    label: "Scenario 5 — Restricted/prohibited tool met hoge exposure",
    departments: ["finance_legal"],
    defaultRepeat: 2,
    profile: {
      department_code: "finance_legal",
      ai_frequency_code: "daily",
      automation_usage_code: "agents_reeks_taken",
      browser_extension_usage_code: "ja_bewust",
    },
    dataTypeCodes: ["financial_data"],
    tool: {
      tool_code: "shadow_agent_x",
      tool_name: "Shadow Agent X",
      is_custom: false,
      catalog_beheerstatus_code: "unknown",
      use_case_code: "systemen_aansturen",
      context_codes: ["kritieke_systemen"],
      account_type_code: "personal_free",
    },
  },
  {
    id: "agentic-automation-outlier",
    label: "Scenario 6 — Agentic/automation-outlier",
    departments: ["it_data_development"],
    defaultRepeat: 3,
    profile: {
      department_code: "it_data_development",
      ai_frequency_code: "daily",
      automation_usage_code: "agents_reeks_taken",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["internal_documents"],
    tool: {
      tool_code: "zapier_ai_agents",
      tool_name: "Zapier AI Agents",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "workflow_uitvoeren",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "hr-evaluation-outlier",
    label: "Scenario 7 — HR/evaluatie-context-outlier",
    departments: ["hr_recruitment"],
    defaultRepeat: 2,
    profile: {
      department_code: "hr_recruitment",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["names"],
    tool: {
      tool_code: "hr_people_analytics",
      tool_name: "HR People Analytics Suite",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "data_analyseren",
      context_codes: ["hr_evaluatie"],
      account_type_code: "business_license",
    },
  },
  {
    id: "small-cluster-directie",
    label: "Scenario 8a — Kleine cluster (directie_management, n=3)",
    departments: ["directie_management"],
    defaultRepeat: 3,
    profile: {
      department_code: "directie_management",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "small-cluster-anders",
    label: "Scenario 8b — Kleine cluster (anders, n=2)",
    departments: ["anders"],
    defaultRepeat: 2,
    profile: {
      department_code: "anders",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "filler-it-data-development",
    label: "Filler — Laag-risicogebruik (it_data_development, n=5)",
    departments: ["it_data_development"],
    defaultRepeat: 5,
    profile: {
      department_code: "it_data_development",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "filler-finance-legal",
    label: "Filler — Laag-risicogebruik (finance_legal, n=5)",
    departments: ["finance_legal"],
    defaultRepeat: 5,
    profile: {
      department_code: "finance_legal",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "filler-hr-recruitment",
    label: "Filler — Laag-risicogebruik (hr_recruitment, n=2)",
    departments: ["hr_recruitment"],
    defaultRepeat: 2,
    profile: {
      department_code: "hr_recruitment",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "filler-sales-account",
    label: "Filler — Laag-risicogebruik (sales_account, n=4)",
    departments: ["sales_account"],
    defaultRepeat: 4,
    profile: {
      department_code: "sales_account",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
  {
    id: "filler-operations",
    label: "Filler — Laag-risicogebruik (operations, n=4)",
    departments: ["operations"],
    defaultRepeat: 4,
    profile: {
      department_code: "operations",
      ai_frequency_code: "weekly",
      automation_usage_code: "alleen_chatbot",
      browser_extension_usage_code: "nee",
    },
    dataTypeCodes: ["public_information"],
    tool: {
      tool_code: "ms_copilot_365",
      tool_name: "Microsoft 365 Copilot",
      is_custom: false,
      catalog_beheerstatus_code: "approved",
      use_case_code: "drafting",
      context_codes: ["internal_work"],
      account_type_code: "business_license",
    },
  },
];

export function findScenario(id: string): ScenarioDefinition | undefined {
  return SCENARIOS.find((scenario) => scenario.id === id);
}
